imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @MongoboxJukeboxBundle/Resources/config/admin.yml }
    - { resource: @MongoboxTumblrBundle/Resources/config/admin.yml }
    - { resource: @MongoboxUsersBundle/Resources/config/admin.yml }
    - { resource: @MongoboxGroupBundle/Resources/config/admin.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:   %locale%
    session:
        gc_maxlifetime:    36000

# Sensio FrameworkExtraBundle
sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }
    view:    { annotations: true }
    cache:   { annotations: true }

# Twig Configuration
twig:
    exception_controller:  twig.controller.exception:showAction
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    globals:
      project_name: MongoBox
      team_name:    Mongo Application
      version:      "1.6"

# Service Configuration
services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
          - { name: twig.extension }
    Mongobox.twig.niceTime_extension:
        class: Mongobox\Bundle\JukeboxBundle\Twig\NiceTimeExtension
        tags:
          - { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

avalanche_imagine:
    source_root:    %kernel.root_dir%/../web/
    web_root:       %kernel.root_dir%/../web/
    cache_prefix:   imagine
    driver:         gd
    filters:
        #Si renommage ou ajout de filters, penser à modifier les lignes de suppression de cache dans User->upload()
        avatar_menu:
            type:    thumbnail
            options: { size: [32, 32], mode: inbox }
        avatar_thumbnail:
            type:    thumbnail
            options: { size: [80, 80], mode: inbox }
        avatar_moyen:
            type:    thumbnail
            options: { size: [50, 50], mode: inbox }
        avatar_mini:
            type:    thumbnail
            options: { size: [20, 20], mode: inbox }

mongoeat_foursquare:
    authentification:
        id:      %foursquare_id%
        secret:  %foursquare_secret%
        url_auth:  "https://foursquare.com/oauth2"
        url_api:  "https://api.foursquare.com/v2"

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_pagination.html.twig     # sliding pagination controls template

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.stats:
            contexts:   [admin]
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks
        sonata.admin.block.search_result:
        sonata.block.service.text:

sonata_admin:
    title:      Mongobox
    #title_logo: /bundles/mongoboxcore/img/logo/mongo-logo-black-little.jpg
    templates:
        # default global templates
        layout:  MongoboxCoreBundle:Admin:standard_layout.html.twig
    dashboard:
        blocks:
            - { position: right, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata.block.service.text, settings: { content: '<div class="box"><div class="box-header with-border"><h2>Bienvenue !</h2></div><div class="box-body">Bienvenue dans la partie administrable du site.</div></div>'} }
            -
               class:    col-lg-4 col-xs-6
               position: top
               type:     sonata.admin.block.stats
               settings:
                   code: sonata.admin.jukebox.video
                   icon: fa-film
                   text: Videos
                   color: bg-red
            -
               class:    col-lg-4 col-xs-6
               position: top
               type:     sonata.admin.block.stats
               settings:
                   code: sonata.admin.tumblr.post
                   icon: fa-pencil-square-o
                   text: Tumblr

            -
               class:    col-lg-4 col-xs-6
               position: top
               type:     sonata.admin.block.stats
               settings:
                   code: sonata.admin.users
                   icon: fa-users
                   text: Users
                   color: bg-green


genemu_form:
    autocomplete: ~