MongoboxTumblrBundle:
    resource: "@MongoboxTumblrBundle/Controller/"
    type:     annotation
    prefix:   /

homepage:
    pattern:  /
    defaults: { _controller: MongoboxJukeboxBundle:Wall:index }
    
MongoboxJukeboxBundle:
    resource: "@MongoboxJukeboxBundle/Controller/"
    type:     annotation
    prefix:   /

MongoboxUsersBundle:
    resource: "@MongoboxUsersBundle/Controller/"
    type:     annotation
    prefix:   /
    
MongoboxGroupBundle:
    resource: "@MongoboxGroupBundle/Controller/"
    type:     annotation
    prefix:   /
    
_login_check:
    pattern: /login_check
    requirements: {_method : POST }

_logout:
    pattern: /logout
        
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_imagine:
    resource: .
    type:     imagine