mongoeat_vote:
    resource: "@MongoeatVoteBundle/Controller/"
    type:     annotation
    prefix:   /

mongoeat_restaurant:
    resource: "@MongoeatRestaurantBundle/Controller/"
    type:     annotation
    prefix:   /

MongoboxTumblrBundle:
    resource: "@MongoboxTumblrBundle/Controller/"
    type:     annotation
    prefix:   /

homepage:
    pattern:  /
    defaults: { _controller: MongoboxCoreBundle:Wall:index }

MongoboxJukeboxBundle:
    resource: "@MongoboxJukeboxBundle/Controller/"
    type:     annotation
    prefix:   /

MongoboxCoreBundle:
    resource: "@MongoboxCoreBundle/Controller/"
    type:     annotation
    prefix:   /

MongoboxUsersBundle:
    resource: "@MongoboxUsersBundle/Controller/"
    type:     annotation
    prefix:   /

MongoboxGroupBundle:
    resource: "@MongoboxGroupBundle/Controller/"
    type:     annotation
    prefix:   /

MongoboxStatisticsBundle:
    resource: "@MongoboxStatisticsBundle/Controller/"
    type:     annotation
    prefix:   /

_login_check:
    pattern: /login_check
    requirements: {_method : POST }

_logout:
    pattern: /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_imagine:
    resource: .
    type:     imagine
