

security:
    encoders:
        Mongobox\Bundle\UsersBundle\Entity\User:
             algorithm: sha512
             iterations: 2000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
         users:
             entity: { class: MongoboxUsersBundle:User, property: login }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            provider:   users
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path:            /
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/$, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/esi, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ]}
        - { path: ^/(login), roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ IS_AUTHENTICATED_FULLY ]}
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
