parameters:
#    mongobox_bookmark.example.class: Mongobox\Bundle\BookmarkBundle\Example

services:
#    mongobox_bookmark.example:
#        class: %mongobox_bookmark.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
